### ISSUE TITLE
Run CI on pinned/unpinned dependencies

### ISSUE THREAD

**Issue by vineetbansal** [raphael-group/paste3#45]
Like we discussed, the `build` and `test` workflows are misnomers, since they both build and test. Let's call them `test-pinned-deps`/`test-unpinned-deps`

- Make all dependencies in `requirements.txt` pinned (by inspecting your own working env, for example).
- Keep all dependencies in `pyproject.toml` unpinned, unless you have specific reason to more specific. 
- `test-pinned-deps` will create a conda env using environment.yml+requirements.txt, and install the package on top of it.
- `test-unpinned-deps` will use an off the shelf python interpreter from github-actions and install the package on top of it.
- Both should report a `pip freeze` somewhere in the workflow so that we can refer back to the logs if/when things break. (there's a flag that makes it report just the version numbers without the os specific tags I think).
- It would be great if both workflows work on win/mac/linux, but if windows doesn't work on first go, I would create an issue and postpone it for later.

**Comment by anushka255** [comment]
Implemented all the above mentioned functionalities.

**Comment by vineetbansal** [comment]
Can we rename the steps according to what they do? I find the current names confusing.

**Comment by anushka255** [comment]
Fixed it!
